### ISSUE TITLE
[RK3399] Kernel 4.4.x fails to build with GCC 9.1.0

### ISSUE THREAD

**Issue by 5schatten** [rockchip-linux/kernel#160]
I tried to compile this [Kernel commit](https://github.com/rockchip-linux/kernel/commit/aa8bacf821e5c8ae6dd8cae8d64011c741659945) for a RK3399 board and used the LibreELEC build system but it failed:
```
In file included from /home/supervisedthinking/git/libreelec-rr/LibreELEC.tv/build.LibreELEC-RK3399.arm-9.1-devel/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/string.h:494,
                 from fs/fs.c:7:
In function 'strncpy',
    inlined from 'fs__env_override' at fs/fs.c:191:2,
    inlined from 'fs__get_mountpoint' at fs/fs.c:197:6:
/home/supervisedthinking/git/libreelec-rr/LibreELEC.tv/build.LibreELEC-RK3399.arm-9.1-devel/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/bits/string_fortified.h:106:10: error: '__builtin_strncpy' specified bound 4096 equals destination size [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
I also tried the latest stable & dev version but all fail with the same errors.

Build log:
https://pastebin.com/v9C8Q6Xi
